import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";
import Image from "next/image";

import { myConfig } from "../config";
import { Jobs } from "../components/jobs";
import Footer ,{ Projects } from "../components/footer";

// import styles from "../styles/Home.module.css";
import { AuthorContentInterface } from "../types";
import GitHubIcon from "../public/images/GitHub-Mark-Light-32px.png";
import PhpIcon from "../public/images/php.svg";
import LaravelIcon from "../public/images/logomark.min.svg";
const JsIcon =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAMAAABiM0N1AAAAclBMVEX33x4AAAD+5R/64R7XwxqLfhH/6B8aFwP03R7bxhuOgBHMuBnVwBoYFgPfyRskIAWYiRLu1x21pBaFeRDp0hyjkxRTSwqqmhVpXw3ArRfFshgxLAZvZA0+OAh2ag4tKQVhWAwQDgNaUQsqJQV8cA9JQgnQi+ziAAAB60lEQVRYhe2WYWOCIBCG5a4RqZkpWbrpVmv//y+OPDChdOg+5vsJBR7vjrvDIFi0aNGiRYsWLXpdYaupu0SrHgUwicoqTgCmYCBkayW2MgZAku9Yq/d0PwEFb7TLgCBlPWV8Lgg+mKXUm2SDeMgcZb7eWSBMXA5jiefpWSDI9e46bz5p9CXnWMTP9HDkAHCgaPumk+0ajYs2wjxljfA//z4IJY1z2o6R/+E7Fu1pfNGASUVix0jHupxiylPQjyaFquD+A4Jjlz6h9D6vJ6AgWN8z8RRPssoGYdVP6ks8v/p7zt3UCG+j3DbCI4t0TmYVbeudyC3UZk7R6leyj/oWI7vHQapr7w+7jpT6OfcMdHuNmUHt/HwbAKkJfp0UJReEd0d4QVPlKAh0hjgJCdW93ZucOo4ECcT1k0D81LMfpHqKzL4ONGgR8kzNh7dPo26KTKIa050WU7kir2kqGgLhirpFipwHDS1+V1Sx1VBV+Urycv/GgF/dwV6Kbi+0t7dR/XWqzbgY7HJYsge1txfWjxOMVcOHxnN3MbV77JzrqRlLbGjsxYVejKJwOafxAqHbz+jaLUY42kYd/roGQIb6Tt5+WH0QRFacTcgPHj9ICJDEZRZtArfJIxebKMuqleSeTW34TxHn/US+vH4BepwS04qX0e8AAAAASUVORK5CYII=";
import VueIcon from "../public/images/vue.png";
const ReactIcon =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K";

const Home: NextPage<{ contents: AuthorContentInterface; jobs: [] }> = ({
  contents,
  jobs,
}) => {
  return (
    <Container>
      <Head>
        <title>AnsarMirzayi.ir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row>
        <Col xs={12} className="A">
          <Row>
            <Col
              xs={4}
              md={4}
              lg={3}
              className="1 max-h-300"
              style={{ height: "300px",display: "flex",alignItems: "center"}}
            >
              {contents.main_image ? (
                <img
                  alt={"ansar mirzayi"}
                  className="full-box mt-lg-2"
                  src={myConfig.Base_URL + contents?.main_image}
                />
              ) : (
                ""
              )}
            </Col>
            <Col
              xs={8}
              md={8}
              lg={9}
              className="1prim mt-md-5 mt-0 information"
            >
              <Row>
                <Col>
                  <div className="mt-md-4 mt-0  name-label">وب سایت رسمی</div>
                </Col>
              </Row>
              <Row>
                <Col>
                  <div className="mt-1 title-middle name-title ">
                    {contents?.user_name}
                  </div>
                </Col>

                <Col className="center-line">
                  <a
                    rel="noreferrer"
                    href="https://www.npmjs.com/~ansaramman"
                    className="logo"
                    target="_blank"
                    title="npm packages"
                  >
                    <svg
                      className="skill-icons"
                      viewBox="0 0 700 700"
                      fill="currentColor"
                    >
                      <polygon
                        fill="#cb0000"
                        points="0,700 700,700 700,0 0,0"
                      ></polygon>
                      <polygon
                        fill="#ffffff"
                        points="150,550 350,550 350,250 450,250 450,550 550,550 550,150 150,150 "
                      ></polygon>
                    </svg>
                  </a>

                  <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://github.com/DevAnsar"
                    className=" ml-3 skill-icons"
                    title="اکانت گیت هاب"
                  >
                    <Image alt="اکانت گیت هاب" src={GitHubIcon} />
                  </a>
                </Col>
              </Row>

              <Row>
                <Col>
                  <div className="mt-3 title-middle name-label min-h-25">
                    فول استک وب
                    {/* <a
                      href="https://www.php.net/"
                      className="ml-3 skill-icons"
                      title="php"
                    >
                      <Image alt="php" src={PhpIcon} />
                    </a>

                    <a
                      href="https://laravel.com"
                      className=" ml-3 skill-icons"
                      title="laravel"
                    >
                      <Image
                        alt="laravel"
                        src={LaravelIcon}
                      />
                    </a>

                    <a
                      href="https://www.javascript.com"
                      className=" ml-3 skill-icons"
                      title="javascript"
                    >
                      <Image
                        alt="javascript"
                        src={JsIcon}
                        layout='fill'
                      />
                    </a>

                    <a
                      href="https://reactjs.org"
                      className=" ml-3 skill-icons"
                      title="reactjs"
                    >
                      <Image
                        alt="reactjs"
                        layout='fill'
                        src={ReactIcon}
                      />
                    </a>

                    <a
                      href="https://vuejs.org/"
                      className=" ml-3 skill-icons"
                      title="vuejs"
                    >
                      <Image
                        alt="vuejs"
                        src={VueIcon}
                      />
                    </a> */}
                  </div>
                </Col>
              </Row>

              <Row>
                <Col>
                  <div className="mt-2 title-middle text-medium min-h-30">
                    {contents?.description}
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
          <Row>
            <Col xs={12} className="1prim mt-md-5 mt-0">
              <Row>
                <Col className="mt-3 mb-1 name-label">نمونه پروژه ها</Col>
              </Row>
              <Row id="jox-box" className={true ? "active" : ""}>
                <Jobs jobs={jobs} />
                {/* {loading ? <Loading /> : ""} */}
              </Row>
              <Row>
                {/* <Col xs={12}>
                  <div className="showMore">
                    {currentPage !== totalPage && (
                      <div
                        className="balance text-medium text-bold btn btn-sm btn-outline-light"
                        onClick={getNextJobs}
                      >
                        ادامه لیست
                      </div>
                    )}
                  </div>
                </Col> */}
              </Row>
            </Col>
          </Row>
        </Col>

        <Projects />
        <Footer />
      </Row>
    </Container>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(myConfig.API_URL + "/v1/index", {
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
  });
  const data = await res.json();
  return {
    props: {
      contents: data.contents,
      jobs: data.jobs,
    },
  };
};
export default Home;
